# **1.Single Perceptron**

In [2]:
import numpy as np
import pandas as pd
import math

X = np.array ([ 0.5, 0.6 , 0.9])
W=np.array ([0.2, 0.3, 0.1] )
b = 0.5
def stepfunction(t):
    if t>0:
       return 1
    else:
       return 0
def prediction (X, W, b):
    return stepfunction((np.matmul(X,W)+b))

print(prediction (X, W, b ))

1


# **2.Implementation of perceptron model in AND gate**

In [3]:
import numpy as np
import random
import sys

and_gate = [
    [(1, 1), 1],
    [(1, -1), -1],
    [(-1, 1), -1],
    [(-1, -1), -1]
]

or_gate = [
    [(1, 1), 1],
    [(1, -1), 1],
    [(-1, 1), 1],
    [(-1, -1), -1]
]


def activation_function(x):
    if x > 0:
        return 1
    elif x < 0:
        return -1
def run_perceptron(gate):
    bias = (1,)
    learning_constant = 0.1
    n = 50
    weights = []
    for i in range(3):
        weights.append(random.uniform(-1, 1))

    for i in range(n):
        inputs, expected_output = random.choice(gate)
        inputs = inputs + bias
        weighted_sum = np.dot(inputs, weights)
        guess = activation_function(weighted_sum)
        error = expected_output - guess
        weights += learning_constant * error * np.asarray(inputs)
    inputs, expected_output = random.choice(gate)
    print("inputs: " + str(inputs))
    inputs = inputs + bias
    weighted_sum = np.dot(inputs, weights)
    print("weighted sum: " + str(weighted_sum))
    print("correct answer: " + str(expected_output))
    print("perceptron guess: " + str(activation_function(weighted_sum)) + '\n')

tests=2
for i in range(tests):
    print("// AND //")
    run_perceptron(and_gate)

    print("// OR //")
    run_perceptron(or_gate)

// AND //
inputs: (1, -1)
weighted sum: -0.3092306309321265
correct answer: -1
perceptron guess: -1

// OR //
inputs: (1, -1)
weighted sum: 1.2460126313467053
correct answer: 1
perceptron guess: 1

// AND //
inputs: (-1, 1)
weighted sum: -0.1740176807277276
correct answer: -1
perceptron guess: -1

// OR //
inputs: (1, 1)
weighted sum: 1.3955594714909192
correct answer: 1
perceptron guess: 1



## **3.Simple neural networks**

In [16]:
import numpy as np
class NeuralNetwork():
    def __init__(self):
        np.random.seed(1)

        self.synaptic_weights = 2 * np.random.random((3, 1)) - 1
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    def sigmoid_derivative(self, x):
        return x * (1 - x)

    def train(self, training_inputs, training_outputs, training_iterations):


        for iteration in range(training_iterations):

            output = self.think(training_inputs)
            error = training_outputs - output
            adjustments = np.dot(training_inputs.T, error * self.sigmoid_derivative(output))
            self.synaptic_weights += adjustments

    def think(self, inputs):
        inputs = inputs.astype(float)
        output = self.sigmoid(np.dot(inputs, self.synaptic_weights))
        return output


In [17]:
if __name__ == "__main__":
  neural_network = NeuralNetwork()
  print("Random starting synaptic weights: ")
  print(neural_network.synaptic_weights)
  training_set_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
  training_set_outputs = array([[0, 1, 1, 0]]).T

  neural_network.train(training_set_inputs, training_set_outputs, 10000)
  print("New synaptic weights after training: ")
  print(neural_network.synaptic_weights)

  print("Considering new situation [1, 0, 0] -> ?: ")
  print(neural_network.think(array([1, 0, 0])))

Random starting synaptic weights: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
New synaptic weights after training: 
[[ 9.67299303]
 [-0.2078435 ]
 [-4.62963669]]
Considering new situation [1, 0, 0] -> ?: 
[0.99993704]


# **4.Multi-layered neural networks**

In [18]:
from numpy import exp, array, random, dot

In [19]:
class NeuronLayer():
    def __init__(self, number_of_neurons, number_of_inputs_per_neuron):
        self.synaptic_weights = 2 * random.random((number_of_inputs_per_neuron, number_of_neurons)) - 1

In [20]:
class NeuralNetwork():
    def __init__(self, layer1, layer2):
        self.layer1 = layer1
        self.layer2 = layer2


    def __sigmoid(self, x):
        return 1 / (1 + exp(-x))

    def __sigmoid_derivative(self, x):
        return x * (1 - x)

    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):
        for iteration in range(number_of_training_iterations):
            output_from_layer_1, output_from_layer_2 = self.think(training_set_inputs)

            layer2_error = training_set_outputs - output_from_layer_2
            layer2_delta = layer2_error * self.__sigmoid_derivative(output_from_layer_2)

            layer1_error = layer2_delta.dot(self.layer2.synaptic_weights.T)
            layer1_delta = layer1_error * self.__sigmoid_derivative(output_from_layer_1)

            layer1_adjustment = training_set_inputs.T.dot(layer1_delta)
            layer2_adjustment = output_from_layer_1.T.dot(layer2_delta)

            self.layer1.synaptic_weights += layer1_adjustment
            self.layer2.synaptic_weights += layer2_adjustment

    def think(self, inputs):
        output_from_layer1 = self.__sigmoid(dot(inputs, self.layer1.synaptic_weights))
        output_from_layer2 = self.__sigmoid(dot(output_from_layer1, self.layer2.synaptic_weights))
        return output_from_layer1, output_from_layer2

    def print_weights(self):
        print("    Layer 1 (4 neurons, each with 3 inputs): ")
        print(self.layer1.synaptic_weights)
        print("    Layer 2 (1 neuron, with 4 inputs):")
        print(self.layer2.synaptic_weights)

In [21]:
if __name__ == "__main__":

    random.seed(1)

    layer1 = NeuronLayer(4, 3)
    layer2 = NeuronLayer(1, 4)
    neural_network = NeuralNetwork(layer1, layer2)

    print ("Stage 1) Random starting synaptic weights: ")
    neural_network.print_weights()

    training_set_inputs = array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [0, 1, 0], [1, 0, 0], [1, 1, 1], [0, 0, 0]])
    training_set_outputs = array([[0, 1, 1, 1, 1, 0, 0]]).T

    neural_network.train(training_set_inputs, training_set_outputs, 60000)

    print("Stage 2- New synaptic weights after training: ")
    neural_network.print_weights()

    print("Stage 3- Considering a new situation [1, 1, 0] -> ?: ")
    hidden_state, output = neural_network.think(array([1, 1, 0]))
    print(output)

Stage 1) Random starting synaptic weights: 
    Layer 1 (4 neurons, each with 3 inputs): 
[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]
    Layer 2 (1 neuron, with 4 inputs):
[[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]]
Stage 2- New synaptic weights after training: 
    Layer 1 (4 neurons, each with 3 inputs): 
[[ 0.3122465   4.57704063 -6.15329916 -8.75834924]
 [ 0.19676933 -8.74975548 -6.1638187   4.40720501]
 [-0.03327074 -0.58272995  0.08319184 -0.39787635]]
    Layer 2 (1 neuron, with 4 inputs):
[[ -8.18850925]
 [ 10.13210706]
 [-21.33532796]
 [  9.90935111]]
Stage 3- Considering a new situation [1, 1, 0] -> ?: 
[0.0078876]
